# Generated by Django 3.2.25 on 2026-09-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Annual Leave', 'Annual Leave'), ('Emergency Leave', 'Emergency Leave'), ('Unpaid Leave', 'Unpaid Leave')], max_length=50),
        ),
    ]
