# Generated by Django 3.2.25 on 2026-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='substitute_choice',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Pending', max_length=20),
        ),
    ]
