# Generated by Django 3.2.25 on 2026-10-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest_substitute_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='substitute_choice',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Reject', 'Reject')], max_length=20, null=True),
        ),
    ]
