# Generated by Django 3.2.25 on 2026-09-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20260921_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='confirmPassword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
