# Generated by Django 3.2.25 on 2026-09-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20260924_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='confirmPassword',
        ),
    ]
