# Generated by Django 3.2.25 on 2026-09-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
