# Generated by Django 3.2.25 on 2026-10-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=100, null=True),
        ),
    ]
